// Code generated by "stringer -type=Token"; DO NOT EDIT.

package token

import "strconv"

const _Token_name = "ILLEGALIDENTINTSTRINGADDSUBMULPOWQUOREMANDORXORSHLSHRAND_NOTASSIGNEQLPARENLBRACKLBRACECOMMAPERIODRPARENRBRACKRBRACESEMICOLONCOLON"

var _Token_index = [...]uint8{0, 7, 12, 15, 21, 24, 27, 30, 33, 36, 39, 42, 44, 47, 50, 53, 60, 66, 68, 74, 80, 86, 91, 97, 103, 109, 115, 124, 129}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
